# Numpy
- create array
- maths
- operation

In [2]:
x = [[1,2,3],[3,2,1]]
print(x)

[[1, 2, 3], [3, 2, 1]]


without numpy doing maths(matrix maths) is very complex in any language

In [1]:
import numpy as np

In [2]:
x = np.array([[1,2,3],[3,4,5]])
print(x)
print(type(x))
print(x.shape)


[[1 2 3]
 [3 4 5]]
<class 'numpy.ndarray'>
(2, 3)


In [3]:
print(x.sum())
print(x.sum(axis=0))
print(x.sum(axis=1))

18
[4 6 8]
[ 6 12]


In [4]:
a = np.array([1,2,3])
b = np.array([[1,1],[2,2],[3,3]])
c = np.array([[[1,1],[2,2],[3,3]]])
print(a.shape, a.ndim)
print(b.shape, b.ndim)
print(c.shape, c.ndim)

(3,) 1
(3, 2) 2
(1, 3, 2) 3


# matrix creation 
- sequential
     - arange
     - linspace
- random
    - rand
    - randint
    - uniform

In [ ]:
x = np.arange(1, 11, .5)     # this make the gap of 0.5 and take the no. between 1 to 11
print(x)

y = np.linspace(1, 11, 20)
print(y)

In [ ]:
np.arange(1, 11, .5).reshape(5,4)  # reshape to 4x5 matrix

In [ ]:
np.arange(-3.14,3.14, .2).reshape(4,8)

In [ ]:
a = np.random.rand(3,1)
a

In [ ]:
np.set_printoptions(precision=2)

In [ ]:
b = np.random.randint(0,10, (3,3))
print(b)

In [ ]:
c = np.random.uniform(0,10, (3,3))
print(c)

# Slicing

In [ ]:
x = np.random.randint(0, 20, 15)
print(x)

In [ ]:
print(x[:5])
print(x[5:])
print(x[-5:])

In [ ]:
z = np.random.randint(0 , 20, (6 , 6))
print(z)

In [ ]:
print('row[0] =>', z[0])
print('row[2,3,4] =>\n', z[2:5])
print('first element =>', z[0,0])
print('last element =>', z[-1,-1])
print('first row , last element =>', z[0,-1])

In [ ]:
print('column 1 =>', z[:, 0])
print('column 5 =>', z[:, 4])
print('column last =>', z[:, -1])
print('column [1,2,3] =>\n', z[:, :4])
print('row 1,2 col 1,2 =>\n', z[:2, :2])

# maths - algebra, statstics, trignometry

In [ ]:
x = np.random.randint(0,20,(2,6))
print(x)

In [ ]:
print(x.mean())      # mean of all elements
print(x.mean(axis=1))    # mean of each row
print(x.mean(axis=0))    # mean of each column
print(x.sum())

In [ ]:
print(np.median(x))
print(x.var())

In [ ]:
print(x.min())
print(x.max())

In [ ]:
print(x.std())
print(x.std(axis=1))
print(x.std(axis=0))

In [ ]:
print(np.sin(x))
print(np.cos(x))
print(np.tan(x))


In [ ]:

x = np.random.randint(0,10,(3,3))
y = np.random.randint(0,20,(3,3))
print(x)
print(y)
print(x*y)
print(x@y)
print(x.dot(x,y))


# Some utilities

In [ ]:
x = np.random.randint(0,20,(2,6))
print(x)

In [ ]:
print(x.T)   # transpose

In [ ]:
print(x.reshape(3,4))

In [ ]:
x.resize(3,4, refcheck=False)
print(x)

# data visualization

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
t  = np.arange(0,3*np.pi, .1)
x = np.sin(t)
y = np.cos(t)
plt.plot(t, x, 'go:')

In [ ]:
plt.plot(t, y, 'go:')

In [ ]:
plt.plot(x,y,'go:')

In [ ]:
plt.plot(t,y,'go:', label='cos(t)')
plt.plot(t,x,'rx:', label='sin(t)')
plt.legend()
plt.grid()

In [ ]:
d = np.random.randn(1000)
plt.hist(d, bins=list(range(-3, 4)))
plt.show()

In [ ]:
d = np.random.randn(1000)
plt.hist(d, bins=50)
plt.show()

In [ ]:
plt.boxplot(x)
plt.show()