# Numpy
- create array
- maths
- operation

In [1]:
x = [[1,2,3],[3,2,1]]
print(x)

[[1, 2, 3], [3, 2, 1]]


without numpy doing maths(matrix maths) is very complex in any language

In [4]:
import numpy as np

In [5]:
x = np.array([[1,2,3],[3,4,5]])
print(x)
print(type(x))
print(x.shape)


[[1 2 3]
 [3 4 5]]
<class 'numpy.ndarray'>
(2, 3)


In [7]:
print(x.sum())
print(x.sum(axis=0))
print(x.sum(axis=1))

18
[4 6 8]
[ 6 12]


In [8]:
a = np.array([1,2,3])
b = np.array([[1,1],[2,2],[3,3]])
c = np.array([[[1,1],[2,2],[3,3]]])
print(a.shape, a.ndim)
print(b.shape, b.ndim)
print(c.shape, c.ndim)

(3,) 1
(3, 2) 2
(1, 3, 2) 3


# matrix creation 
- sequential
     - arange
     - linspace
- random
    - rand
    - randint
    - uniform

In [16]:
x = np.arange(1, 11, .5)     # this make the gap of 0.5 and take the no. between 1 to 11
print(x)

y = np.linspace(1, 11, 20)
print(y)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10.  10.5]
[ 1.          1.52631579  2.05263158  2.57894737  3.10526316  3.63157895
  4.15789474  4.68421053  5.21052632  5.73684211  6.26315789  6.78947368
  7.31578947  7.84210526  8.36842105  8.89473684  9.42105263  9.94736842
 10.47368421 11.        ]


In [18]:
np.arange(1, 11, .5).reshape(5,4)  # reshape to 4x5 matrix

array([[ 1. ,  1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ,  4.5],
       [ 5. ,  5.5,  6. ,  6.5],
       [ 7. ,  7.5,  8. ,  8.5],
       [ 9. ,  9.5, 10. , 10.5]])

In [23]:
np.arange(-3.14,3.14, .2).reshape(4,8)

array([[-3.14, -2.94, -2.74, -2.54, -2.34, -2.14, -1.94, -1.74],
       [-1.54, -1.34, -1.14, -0.94, -0.74, -0.54, -0.34, -0.14],
       [ 0.06,  0.26,  0.46,  0.66,  0.86,  1.06,  1.26,  1.46],
       [ 1.66,  1.86,  2.06,  2.26,  2.46,  2.66,  2.86,  3.06]])

In [26]:
a = np.random.rand(3,1)
a

array([[0.2079756 ],
       [0.06494741],
       [0.1187498 ]])

In [28]:
np.set_printoptions(precision=2)

In [29]:
b = np.random.randint(0,10, (3,3))
print(b)

[[0 9 3]
 [2 6 6]
 [1 6 4]]


In [30]:
c = np.random.uniform(0,10, (3,3))
print(c)

[[3.8  8.57 2.8 ]
 [1.62 9.15 9.46]
 [2.43 0.68 5.99]]
