# Numpy
- create array
- maths
- operation

In [1]:
x = [[1,2,3],[3,2,1]]
print(x)

[[1, 2, 3], [3, 2, 1]]


without numpy doing maths(matrix maths) is very complex in any language

In [4]:
import numpy as np

In [5]:
x = np.array([[1,2,3],[3,4,5]])
print(x)
print(type(x))
print(x.shape)


[[1 2 3]
 [3 4 5]]
<class 'numpy.ndarray'>
(2, 3)


In [7]:
print(x.sum())
print(x.sum(axis=0))
print(x.sum(axis=1))

18
[4 6 8]
[ 6 12]


In [8]:
a = np.array([1,2,3])
b = np.array([[1,1],[2,2],[3,3]])
c = np.array([[[1,1],[2,2],[3,3]]])
print(a.shape, a.ndim)
print(b.shape, b.ndim)
print(c.shape, c.ndim)

(3,) 1
(3, 2) 2
(1, 3, 2) 3


# matrix creation 
- sequential
     - arange
     - linspace
- random
    - rand
    - randint
    - uniform

In [16]:
x = np.arange(1, 11, .5)     # this make the gap of 0.5 and take the no. between 1 to 11
print(x)

y = np.linspace(1, 11, 20)
print(y)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10.  10.5]
[ 1.          1.52631579  2.05263158  2.57894737  3.10526316  3.63157895
  4.15789474  4.68421053  5.21052632  5.73684211  6.26315789  6.78947368
  7.31578947  7.84210526  8.36842105  8.89473684  9.42105263  9.94736842
 10.47368421 11.        ]


In [18]:
np.arange(1, 11, .5).reshape(5,4)  # reshape to 4x5 matrix

array([[ 1. ,  1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ,  4.5],
       [ 5. ,  5.5,  6. ,  6.5],
       [ 7. ,  7.5,  8. ,  8.5],
       [ 9. ,  9.5, 10. , 10.5]])